### ISSUE TITLE
Where does pingu store the host list?

### ISSUE THREAD

**Issue by vkoechli** [attheodo/Pingu#8]
I'd like to remove a host from the list. I know that I can add 5 to flush everything out of the fifo list, but that's not what I want. I want one host less, not 4 more.
Where ist the host list stored? Can I edit it, or just delete it and start afresh?

**Comment by attheodo** [comment]
Hey @vkoechli,

Pingu saves the host in `UserDefaults`.

You might want to try using the `defaults read/write` CLI tool to edit the file. It normally resides in `/Library/Containers/com.attheodo.Pingu/Data/Library/Preferences`
